### PR TITLE
Upgrade to terraform 0.13

### PR DESCRIPTION
**Pull request by dheles**

### CODE REVIEW

**Comment by bbranan** [comment]
Just a note that when we tried updating to Terraform 0.13 last week we ran into this issue: https://github.com/hashicorp/terraform/issues/25752 which is now fixed in 0.13.1. I'm just calling it out in case you want to go ahead and bump to 0.13.1, just to avoid the potential of a problem.

**Comment by dheles** [comment]
Thanks, @bbranan .

It isn't obvious from this PR, but I also ran onto the issue with 0.13.0 and was able to succeed with 0.13.1. The `terraform 0.13upgrade` tool made these changes without specifying a point version, so I left things as-is, relying on agreement to not try to use 0.13.0. In my testing, using it didn't break anything, it just didn't work.

In your repo, did you hand-edit to specify a point version (I can't seem to find it to check)?

**Comment by bbranan** [comment]
When we ran into the issue 0.13.1 hadn't been released yet, so we just backed out the upgrade to continue with 0.12.29 until the problem was resolved. We haven't yet made it back to test with 0.13.1.

**Comment by dheles** [comment]
Hand-edited to require 0.13.1 & re-tested enough to confirm that terraform will to roll with & enforce the change.

**Review by jonathangreen — APPROVED** [review]
Looks good to me.

**Pull request merged**
